In [1]:
#!/usr/bin/python
# -*- coding: utf-8 -*-
# ========== python ==========
import os
from logging import Logger
from pathlib import Path
# noinspection PyUnresolvedReferences
from typing import List, Dict, Tuple, Optional, Union, Callable, Final, Literal, get_args
PROJECT_DIR = Path().resolve().parents[0]
os.chdir(PROJECT_DIR)

In [2]:
import torch

In [3]:
from src.run import setup, setup_parser, train_setup
from src.utils.progress_manager import ProgressHelper 

In [4]:
args_list = [
    '--notebook', 
    '--logfile', './log/test.log',
    '--param-file', './log/test.param',
    '--console-level', 'info',
    '--device-name', 'cuda',
    '--KGdata', 'KGC-ALL-SVO',
    '--entity-special-num', 0, '--relation-special-num', 0,
    '--model', 'conve',
    '--model-path', 'saved_models/1113/01/model.pth', 
    '--batch-size', '1', '--train-type', 'all_tail',
]
args, logger, device = setup(setup_parser, PROJECT_DIR, parser_args=args_list)

2022-11-14 09:45:36 - INFO - torch.py - 75 - use gpu


In [5]:
args.device = device
args.progress_helper = ProgressHelper("log/progress.{pid}.txt", pid=args.pid)
data_helper, model = train_setup(args, logger=logger)

2022-11-14 09:45:42 - INFO - run.py - 661 - load data start
2022-11-14 09:45:42 - INFO - data_helper.py - 397 - ==========Show DataHelper==========
2022-11-14 09:45:42 - INFO - data_helper.py - 398 - ==========
2022-11-14 09:45:42 - INFO - data_helper.py - 179 - ==========Show MyRawData==========
2022-11-14 09:45:42 - INFO - data_helper.py - 180 - entity_length: 7196
2022-11-14 09:45:42 - INFO - data_helper.py - 181 - relation_length: 1322
2022-11-14 09:45:42 - INFO - data_helper.py - 182 - er_list length: 6768
2022-11-14 09:45:42 - INFO - data_helper.py - 183 - ==========Show MyRawData==========
2022-11-14 09:45:42 - INFO - data_helper.py - 400 - ==========
2022-11-14 09:45:42 - INFO - data_helper.py - 401 - entity_special_num: 0
2022-11-14 09:45:42 - INFO - data_helper.py - 402 - relation_special_num: 0
2022-11-14 09:45:42 - INFO - data_helper.py - 403 - ==========Show DataHelper==========
2022-11-14 09:45:42 - INFO - run.py - 663 - load data end
2022-11-14 09:45:42 - INFO - run.py -

In [40]:
from utils.torch import load_model
model.init()
load_model(model, args.model_path, args.device)
model.eval()

ConvE(
  (emb_e): Embedding(7196, 200)
  (emb_rel): Embedding(1322, 200)
  (inp_drop): Dropout(p=0.2, inplace=False)
  (hidden_drop): Dropout(p=0.3, inplace=False)
  (feature_map_drop): Dropout2d(p=0.2, inplace=False)
  (loss): BCELoss()
  (conv1): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), bias=False)
  (bn0): BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (bn2): BatchNorm1d(200, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc): Linear(in_features=9728, out_features=200, bias=True)
)

In [8]:
entity_dict = {name: i for i, name in enumerate(data_helper.processed_entities)}
relation_dict = {name: i for i, name in enumerate(data_helper.processed_relations)}
entity_dict.keys()

dict_keys(['AllTitle:Holmes', 'AllTitle:Watson', 'ACaseOfIdentity:Woman', 'ResidentPatient:police_officer', 'CrookedMan:Monday', 'ResidentPatient:Helper_boy', 'AbbeyGrange:Residents_of_Abbey_Grange', 'AbbeyGrange:Sir_Eustace_Brackenstall', 'SilverBlaze:Silas_Brown', 'CrookedMan:dwelleers_of_mountain', 'DevilsFoot:Mortimer', 'AbbeyGrange:police', 'AbbeyGrange:Sailor', 'SpeckledBand:Roylott', 'ACaseOfIdentity:Ned', 'SilverBlaze:Gypsy', 'ACaseOfIdentity:Man', 'SpeckledBand:coroner', 'AbbeyGrange:Mary', 'AbbeyGrange:siblings_of_Lady_Brackenstall', 'DancingMen:Maid', 'SilverBlaze:Subordinates_of_Silas_Brown', 'SilverBlaze:Wasteland', 'SilverBlaze:Gypsy_of_Dartmoor', 'SpeckledBand:mother_of_sister', 'ResidentPatient:Robbery_of_the_indentation', 'AbbeyGrange:eight_maids', 'ResidentPatient:Lanner_Inspector', 'CrookedMan:guest', 'SilverBlaze:Criminal', 'ACaseOfIdentity:father_of_Sutherland', 'SpeckledBand:lieutenant_commander', 'DancingMen:Willson', 'CrookedMan:doctor', 'ResidentPatient:Face_of

In [9]:
len(data_helper.data.id2count_relation), data_helper.data.relation_length

(1322, 1322)

In [30]:
for key in relation_dict:
    print(key) if 'kill' in key else None
    print(key) if 'hide' in key else None
    print(key) if 'die' in key else None
    print(key) if 'take' in key else None

word.predicate:die
word.predicate:takeWalk
word.predicate:takeDown
word.predicate:hideAway
word.predicate:takeAlong
word.predicate:take
word.predicate:takeAway
word.predicate:kill
word.predicate:takeOff
word.predicate:takeOut
word.predicate:hide
word.predicate:die_REVERSE
word.predicate:takeWalk_REVERSE
word.predicate:takeDown_REVERSE
word.predicate:hideAway_REVERSE
word.predicate:takeAlong_REVERSE
word.predicate:take_REVERSE
word.predicate:takeAway_REVERSE
word.predicate:kill_REVERSE
word.predicate:takeOff_REVERSE
word.predicate:takeOut_REVERSE
word.predicate:hide_REVERSE


In [19]:
for key in relation_dict:
    

word.predicate:hideAway
word.predicate:hide
word.predicate:hideAway_REVERSE
word.predicate:hide_REVERSE


In [49]:
# julia
for key in entity_dict:
    print(key, entity_dict[key]) if ':Julia' in key else None
    print(key, entity_dict[key]) if ':Brenda' in key else None
    print(key, entity_dict[key]) if ':Mortimer' in key else None
    print(key, entity_dict[key]) if ':Blessington' in key else None
    print(key, entity_dict[key]) if ':Hosmer' in key else None
    print(key, entity_dict[key]) if ':Berkeley' in key else None
    print(key, entity_dict[key]) if ':Windibank' in key else None
    

DevilsFoot:Mortimer 10
ResidentPatient:Blessington 54
DevilsFoot:Brenda 68
ACaseOfIdentity:Hosmer 142
ACaseOfIdentity:Windibank 175
SpeckledBand:Julia 176
ResidentPatient:Blessington_bedroom 4203
ACaseOfIdentity:Hosmer_s_statement 4264
SpeckledBand:Julia_was_losing_on_the_day_Julia_died 4366
DevilsFoot:Brenda' 4666
word.predicate:Julia 5156
ACaseOfIdentity:Hosmer_s_thoughts 5213
word.predicate:Hosmer_Aingel 5339
DevilsFoot:Mortimer_sImmediate_family 5418
SpeckledBand:Julia_s_bedroom 5586
word.predicate:Mortimer 5743
word.predicate:Hosmer 5876
SpeckledBand:Julia_suffered_from_the_smell_of_Indian_cigarettes 6201
word.predicate:Brenda 6218
ResidentPatient:Blessington_room 6219
word.predicate:Blessington 6251
SpeckledBand:Julia_suffered_from_the_smell 6305
word.predicate:Windibank 6455
DevilsFoot:Mortimer_Bed 6854
ACaseOfIdentity:Windibank_s_Thoughts 6954
ResidentPatient:Blessington_bed 7001


In [28]:
# julia
for key in entity_dict:
    print(key, entity_dict[key]) if 'SilverBlaze:' in key else None
    

SilverBlaze:Silas_Brown 8
SilverBlaze:Gypsy 15
SilverBlaze:Subordinates_of_Silas_Brown 21
SilverBlaze:Wasteland 22
SilverBlaze:Gypsy_of_Dartmoor 23
SilverBlaze:Criminal 29
SilverBlaze:horse_trainer_of_Colonel_Ross 35
SilverBlaze:horse_trainer 36
SilverBlaze:two_young_men 47
SilverBlaze:Inspector_Gregory 48
SilverBlaze:Man 50
SilverBlaze:Stableman 58
SilverBlaze:jockey 59
SilverBlaze:John_Straker 69
SilverBlaze:Various_people 71
SilverBlaze:Ned_Hunter_and_two_young_men 80
SilverBlaze:Bookmaker_of_a_small_gambling 88
SilverBlaze:Colonel_Ross 92
SilverBlaze:Jockey_of_Colonel_Ross 94
SilverBlaze:A_group_of_Gypsy 101
SilverBlaze:People 108
SilverBlaze:Fitzroy_Simpson 111
SilverBlaze:William_Derbyshire 113
SilverBlaze:Wife_of_John_Straker 114
SilverBlaze:Two_young_men 126
SilverBlaze:Owner 130
SilverBlaze:Jockey 141
SilverBlaze:police 144
SilverBlaze:Ned_Hunter 145
SilverBlaze:children 146
SilverBlaze:Silver_Blaze 160
SilverBlaze:Lord_Backwater 162
SilverBlaze:Gregory_Inspector 166
SilverBla

In [29]:
e= torch.tensor([
    entity_dict['SpeckledBand:Julia'], 
    entity_dict['DevilsFoot:Mortimer'],
    entity_dict['DevilsFoot:Brenda'],
    entity_dict['ResidentPatient:Blessington'],
    entity_dict['AbbeyGrange:Sir_Eustace_brackenstall'],
    entity_dict['ACaseOfIdentity:Hosmer'],
    entity_dict['CrookedMan:Barclay'],
    entity_dict['SilverBlaze:Silver_Blaze'],
])

In [31]:
r=torch.tensor([
    relation_dict['word.predicate:kill_REVERSE'], 
    relation_dict['word.predicate:kill_REVERSE'],
    relation_dict['word.predicate:kill_REVERSE'],
    relation_dict['word.predicate:kill_REVERSE'],
    relation_dict['word.predicate:kill_REVERSE'],
    relation_dict['word.predicate:hide_REVERSE'],
    relation_dict['word.predicate:die'],
    relation_dict['word.predicate:take_REVERSE'],
])

In [32]:
e, r

(tensor([176,  10,  68,  54,  41, 142,  52, 160]),
 tensor([1176, 1176, 1176, 1176, 1176, 1286,  110, 1150]))

In [35]:
e = e.reshape(8,1)
r = r.reshape(8,1)

In [36]:
e, r

(tensor([[176],
         [ 10],
         [ 68],
         [ 54],
         [ 41],
         [142],
         [ 52],
         [160]]),
 tensor([[1176],
         [1176],
         [1176],
         [1176],
         [1176],
         [1286],
         [ 110],
         [1150]]))

In [38]:
e, r = e.to(device), r.to(device)

In [41]:
pred = model((e,r))

In [45]:
sorted_ = torch.argsort(pred, dim=1, descending=True)

In [50]:
answer_= [
    ('SpeckledBand:Roylott', ),
    ('DevilsFoot:Sterndale', ), 
    ('DevilsFoot:Mortimer', ), 
    ('ResidentPatient:Elderly_man', 'ResidentPatient:Young_man', 'ResidentPatient:Helper_boy'),
    ('AbbeyGrange:Jack_Croker',),
    ('ACaseOfIdentity:Windibank',),
    ('CrookedMan:apoplexia',),
    ('SilverBlaze:John_Straker',)
]
answer_

[('SpeckledBand:Roylott',),
 ('DevilsFoot:Sterndale',),
 ('DevilsFoot:Mortimer',),
 ('ResidentPatient:Elderly_man',
  'ResidentPatient:Young_man',
  'ResidentPatient:Helper_boy'),
 ('AbbeyGrange:Jack_Croker',),
 ('ACaseOfIdentity:Windibank',),
 ('CrookedMan:apoplexia',),
 ('SilverBlaze:John_Straker',)]

In [53]:
entities = data_helper.processed_entities
for i in range(8):
    _ans = answer_[i]
    print(f"----------Answer={', '.join(_ans)}----------")
    for j in range(30):
        print(entities[sorted_[i][j]])
    print("--------------------")

----------Answer=SpeckledBand:Roylott----------
SpeckledBand:the_day_Julia_died
SpeckledBand:Julia
DevilsFoot:criminal
DateTime:1881-04-01T23:30:00
SpeckledBand:1881-04-01T23:30
SpeckledBand:Roylott
SpeckledBand:Helen
SpeckledBand:animal_of_India
SpeckledBand:doctor_of_Stoke_Moran
CrookedMan:man
SilverBlaze:Silver_Blaze
AbbeyGrange:Jack_Croker
SpeckledBand:Julia_s_bedroom
SpeckledBand:250_GBP
SpeckledBand:Roylott_s_bedroom_OR_garden_of_Roylott_OR_Helen_s_bedroom
SpeckledBand:body_of_Julia
SpeckledBand:1881-04-01T03
SpeckledBand:limbs
SilverBlaze:051
SpeckledBand:lieutenant_commander
SilverBlaze:052
ResidentPatient:unexpected_events
SpeckledBand:2_years_ago
SpeckledBand:intense_fear
SpeckledBand:scar
DateTime:1881-04-01T03:00:00
SpeckledBand:one_match_cinders
SpeckledBand:058
DateTime:1880-12-24T10:00:00
ACaseOfIdentity:mother_of_Sutherland
--------------------
----------Answer=DevilsFoot:Sterndale----------
DevilsFoot:Sterndale
DevilsFoot:money
DevilsFoot:Doctor_Richard
DevilsFoot:Port