In [1]:
import torch

In [5]:
triple: torch.Tensor = torch.tensor([
    [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]
    ]
])
valid_filter: torch.Tensor = torch.tensor([
    [
        False, True, False
    ]
])
mask_token_e = 9

valid_ans_story = triple[:, :, 0][valid_filter]
valid_ans_relation = triple[:, :, 1][valid_filter]
valid_ans_object = triple[:, :, 2][valid_filter]

triple_for_valid = triple.clone()
triple_for_valid[:, :, 0][valid_filter] = mask_token_e
triple_for_valid

tensor([[[0, 1, 2],
         [9, 4, 5],
         [6, 7, 8]]])

In [6]:
triple

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])

In [7]:
valid_ans_story

tensor([3])